### PR TITLE
Add macOS support.

### PR DESCRIPTION
**Pull request by RyPoints**
Already works.  Already been using it.  Just needs to be added to the podspec.

### CODE REVIEW

**Comment by RyPoints** [comment]
Ah, looks like because of updates with UIImage/NSImage you also need the changes here: https://github.com/RyPoints/DataCache/commit/be9836986e337977947b5a9fe6c35a7968ac697c

You could just #ifdef a little in DataCache.swift and support macOS though.

**Comment by huynguyencong** [comment]
But you have changed the code to Cocoa and NSImage, it won't work on iOS anymore, will it?

**Comment by RyPoints** [comment]
Yeah, it won't like that.  That's just for me on macOS.  You can easily support both though via wrapping my code and using:

```
#if os(OSX)
    import Cocoa
#elseif os(iOS)
    import UIKit
#endif
```

**Comment by huynguyencong** [comment]
This supports macOS but doesn't support iOS. I will close it.

**Pull request closed without merging**
